package tests;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import utils.XLUtility;

public class GetAllUsersTest extends BaseTest {

    @Test(dataProvider = "getTestData")
    public void testGetAllUsers(String testType,
                                String testName,
                                String baseUrl,
                                String endpoint,
                                String username,
                                String password,
                                String expectedResult,
                                int rowIndex) {

        String token = getAuthToken(baseUrl, username, password);

        Response response = RestAssured.given()
                .baseUri(baseUrl)
                .header("Authorization", "Bearer " + token)
                .when()
                .get(endpoint)
                .then()
                .extract()
                .response();

        try {
            if ("PASS".equalsIgnoreCase(expectedResult)) {
                response.then().statusCode(200);
            } else {
                response.then().statusCode(403);
            }

            XLUtility.setCellData("Tests", rowIndex, 7, "PASS");
        } catch (AssertionError e) {
            try { XLUtility.setCellData("Tests", rowIndex, 7, "FAIL"); } catch (Exception ignored) {}
            throw e;
        } catch (Exception io) { io.printStackTrace(); }
    }

    @DataProvider
    public Object[][] getTestData() throws Exception {
        return XLUtility.getTestData("Tests");
    }
}
