package tests;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import utils.XLUtility;

public class GetAllUsersTest extends BaseTest {

    @DataProvider(name = "testData")
    public Object[][] getTestData() throws Exception {
        return XLUtility.getTestData("Tests");
    }

    @Test(dataProvider = "testData")
    public void testGetAllUsers(
            String testType,
            String testName,
            String baseUrl,
            String endpoint,
            String username,
            String password,
            String expectedResult,
            String status,
            String rowIndexStr
    ) throws Exception {

        int rowIndex = Integer.parseInt(rowIndexStr);

        if (!"GetAllUsers".equalsIgnoreCase(testType)) {
            return; // skip if not this test
        }

        String token = getAuthToken(baseUrl, username, password);

        Response response = RestAssured.given()
                .baseUri(baseUrl)
                .header("Authorization", "Bearer " + token)
                .when()
                .get(endpoint);

        System.out.println("GetAllUsers Response: " + response.asString());

        try {
            if ("PASS".equalsIgnoreCase(expectedResult)) {
                response.then().statusCode(200);
            } else {
                response.then().statusCode(403);
            }
            XLUtility.setCellData("Tests", rowIndex, 7, "PASS");
        } catch (AssertionError e) {
            XLUtility.setCellData("Tests", rowIndex, 7, "FAIL");
            throw e;
        }
    }
}
